                            @startuml

skinparam classFontSize 12
skinparam classAttributeIconSize 0
IManejador <-right-AppSolicitud
CajeroAutomatico<|..IManejador
IManejador <-down-o CajeroAutomatico

CajeroAutomatico<--Billete100
Billete100-right->Billete50
Billete50-right->Billete20
Billete20-right->Billete10
Billete10-right->Billete5


class AppSolicitud{
    +main()
}

interface IManejador{
    +setNext(siguiente:IManejador)
    +procesarSolicitud(cantidad:int)
}

class CajeroAutomatico{
    -cadena:IManejador

    +CajeroAutomatico()
    +dispensar(cantidad:int)
}

class Billete100{
    ...
    +procesarSolicitud(cantidad:int)
}

class Billete50{
    ...
    +procesarSolicitud(cantidad:int)
}

class Billete20{
    ...
    +procesarSolicitud(cantidad:int)
}
class Billete10{
    ...
    +procesarSolicitud(cantidad:int)
}

class Billete5{
    ...
    +procesarSolicitud(cantidad:int)
}
@enduml
